<?php

/*
 * KingAuthor -- a shitty static template-based blog
 * system, written for no reason other than "why not."
 * 
 * This system is proprietary and not really meant for
 * external use. If you've gained access to this code,
 * congratulations, let me know how so I can unfuck my
 * security schema.
 * 
 * Copyright 2019-2020 William Preston / Turnip Collective
 * 
 * Please don't redistribute this code.
 */

define('LOCKOUT', 1);
require('./core/global.php');

?>
<!DOCTYPE html>
<html>
    <head>
        <title>KingAuthor Static CMS</title>
        <?php include('./templates/head.template.php'); ?>
        <script type="text/javascript">
            var articleMappings = [];
        </script>
    </head>
    <body>
    <h1>KingAuthor Static CMS</h1>
        <div id="main-content">
            <h2>Dashboard</h2>
            <div id="content-inner">
                <noscript>
                    KingArthur is meant to run sandboxed or on a local dev environment. You need to enable JavaScript for full functionality. Sorry.
                </noscript>
                <div id="dash-accordion">
                    <h3 class="mouseover">Blog Overview</h3>
                    <div class="accordion-section">
                        <div class="flexbuttons">
                            <button class="dash" type="button" onclick="newPostButton()">New Post</button>
                        </div>
                        <div class="flexbuttons">
                            <button class="dash-gold" type="button" onclick="editButton()">Edit Selected</button><button class="dash-red" type="button" onclick="deleteButton()">Delete Selected</button>
                        </div>
                        <p id="nothing-to-show">No posts could be found.</p>
                        <ul class="article-listing">
                            <?php
                                $articles = $db->getAllPosts();
                                $truncLen = 35;
                                foreach ($articles as $article) {
                                    ?>
                                    <script type="text/javascript">
                                        // generated by PHP
                                        articleMappings.push(<?php print $article['id']; ?>);
                                    </script>
                                    <?php
                            ?>
                            <li>
                                <h4><?php print $article['title']; ?></h4>
                                <p>
                                    <?php 
                                        if ($articles['hidden'] == true) {
                                            ?>
                                            <strong>(Draft)</strong> 
                                            <?php
                                        }
                                        
                                        print (strlen($article['content']) > $truncLen ? substr($article['content'],0,$truncLen)."..." : $in);
                                    ?>
                                </p>
                            </li>
                                    <?php
                                }
                            ?>
                        </ul>
                    </div>
                    
                    <h3 class="mouseover">Rebuild Content</h3>
                    <div class="accordion-section">
                        <div class="switch-wrapper">
                            <div class="onoffswitch">
                                <input type="checkbox" name="rebuild-all" class="onoffswitch-checkbox" id="publicmodeswitch">
                                <label class="onoffswitch-label" for="publicmodeswitch"></label>
                            </div>
                            <p><strong>Rebuild All</strong> - <span class="description">Check this to purge templated files that are already in the output directory. This will force a rebuild of every article and every page, even ones that have been previously built. This can cause the operation to take longer, so use this with discretion.</span></p>
                        </div>
                        <button class="submit" style="width:100%;" type="button">Rebuild Content</button>    
                    </div>
                </div>
            </div>
            <?php include('./templates/copyright.template.php'); ?>
        </div>
        <script type="text/javascript">
            var acc = $('#dash-accordion');
            acc.accordion({
                heightStyle: "content"
            });
            
            var articles = $('.article-listing > li');
            // I know that using the window object is cardinal sin, but this is supposed
            // to be sandboxed, so if you're running this live somewhere and you get XSS'd,
            // it's your own fault.
            var selectedArticle = -1;
            articles.click(function(){
                articles.removeClass('selected');
                $(this).addClass('selected');  
                selectedArticle = $(this).index()-1;
            });
            
            function newPostButton() {
                window.location.href = "editor.php";
            }

            function editButton() {
                if (selectedArticle == -1) return;
                window.location.href = "editor.php?article=" + articleMappings[selectedArticle];
            }

            function deleteButton() {
                if (selectedArticle == -1) return;
                if (confirm("Are you sure you want to delete this post?")) {
                    window.location.href = "editor.php?article=" + articleMappings[selectedArticle] + "&delete=true";
                }
            }
        </script>
    </body>
</html>